TOPICS = [
    "Kubernetes Cost Optimization",
    "GitOps with ArgoCD",
    "Terraform State Management",
    "Platform Engineering",
    "MLOps Pipelines",
    "FinOps for Cloud",
    "Observability",
    "SRE Error Budgets",
    "Docker Multi-Stage Builds",
    "DevSecOps",
    "Helm Chart Authoring",
    "Service Mesh (Istio/Linkerd)",
    "CI/CD Pipeline Design",
    "FluxCD / Flux v2",
    "Pulumi / CDK",
    "Crossplane",
    "Distributed Tracing",
    "Chaos Engineering",
    "Supply Chain Security (SLSA)",
    "Secrets Management",
    "Policy as Code (OPA/Kyverno)",
    "Developer Experience (DX)",
    "Kubernetes Operators",
    "AI-Assisted DevOps",
    "Data Pipeline Infra",
    "GitOps",
    "ArgoCD",
    "Terraform",
    "Kubernetes",
    "DevSecOps",
    "Platform Engineering",
    "MLOps",
    "Observability",
    "FinOps",
    "SRE"
]

STYLES = [
    "lesson_learned",
    "hot_take",
    "mistake_post",
    "tool_comparison",
    "trend_opinion"
]